name: riverpod_async_value_sync
description: AsyncValue synchronization method
version: 0.0.1
homepage: https://github.com/klaus-moon/riverpod_async_value_sync

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  riverpod: ^2.3.7
